//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MultiSEngine.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MultiSEngine.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 {
        ///  &quot;Command_IsSwitching&quot;: &quot;正在跳转中, 请勿使用此命令&quot;,
        ///  &quot;Command_AlreadyIn&quot;: &quot;你已处于服务器 {0} 中&quot;,
        ///  &quot;Command_Switch&quot;: &quot;正在传送至服务器 {0}&quot;,
        ///  &quot;Command_Back&quot;: &quot;已返回主服务器&quot;,
        ///  &quot;Command_AviliableServer&quot;: &quot;可用的服务器: &quot;,
        ///  &quot;Command_ServerNotFound&quot;: &quot;未找到含有关键词 {0} 的服务器&quot;,
        ///  &quot;Command_NotEntered&quot;: &quot;你目前尚未进入任何服务器, 以下为可用指令:&quot;,
        ///
        ///  &quot;Help_Tp&quot;: &quot;/mse tp([c/B3CE95:t]) &lt;[c/B3CE95:服务器名]&gt; -- 传送到指定服务器&quot;,
        ///  &quot;Help_Back&quot;: &quot;/mse back([c/B3CE95:b]) -- 传送回主服务器&quot;,
        ///  &quot;Help_List&quot;: &quot;/mse list([c/B3CE95:l]) -- 列出所有可用的服务器&quot;,
        ///  &quot;Help_Command&quot;: &quot;/mse command( [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string DefaultLocallization {
            get {
                return ResourceManager.GetString("DefaultLocallization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 欢迎来到 {name} 服务器!
        ///当前服务器在线 [C/97ADD6:{online}] 人: {players}
        ///可用服务器: [C/B1DAE4:{servers}]
        ///使用 [C/B6E1C1:/mse tp &lt;服务器名&gt;] 来传送到指定服务器 的本地化字符串。
        /// </summary>
        internal static string DefaultMotd {
            get {
                return ResourceManager.GetString("DefaultMotd", resourceCulture);
            }
        }
    }
}
